require("./jquery-3.3.1.min");
require("./bootstrap");
require("./player");
require("./jquery.nice-select.min");
require("./mixitup.min");
require("./mixitup.min");
require("./jquery.slicknav");
require("./owl.carousel.min");
require("./main");
